export const STUDY_TIPS = [
    "Use the Pomodoro Technique: Study for 25 minutes, then take a 5-minute break.",
    "Space out your study sessions over several days rather than cramming.",
    "Teach what you've learned to someone else to reinforce your understanding.",
    "Practice active recall by testing yourself frequently.",
    "Create mind maps to visualize connections between different concepts.",
    "Get enough sleep—it's essential for memory consolidation.",
    "Stay hydrated; even mild dehydration can affect your concentration.",
    "Switch between subjects during a study session to keep your brain engaged.",
    "Eliminate distractions like your phone and social media while studying.",
    "Use mnemonic devices to remember complex information.",
    "Keep your study area clean and organized to reduce mental clutter.",
    "Rewrite your notes in your own words to ensure you understand the material.",
    "Listen to white noise or ambient sounds if you find complete silence distracting.",
    "Set specific, achievable goals for each study session.",
    "Take handwritten notes—it often leads to better retention than typing.",
    "Use the Feynman Technique: Explain a topic in simple terms to find gaps in your knowledge.",
    "Eat brain-boosting foods like blueberries, nuts, and dark chocolate.",
    "Review your notes within 24 hours of taking them.",
    "Use visual aids like charts, diagrams, and colored pens.",
    "Take regular breaks to avoid burnout and keep your focus sharp.",
    "Practice mindfulness or meditation to reduce study-related stress.",
    "Find a study buddy to keep each other accountable.",
    "Break down large tasks into smaller, more manageable steps.",
    "Reward yourself after completing a challenging study goal.",
    "Use flashcards for quick review of key terms and facts.",
    "Change your study environment occasionally to boost memory recall.",
    "Avoid multitasking; focus on one task at a time for maximum efficiency.",
    "Stay positive and believe in your ability to learn and succeed.",
    "Use the SQ3R method: Survey, Question, Read, Recite, Review.",
    "Relate new information to things you already know.",
    "Summarize each chapter or section after you finish reading it.",
    "Ask questions in class or during study sessions to clarify your understanding.",
    "Use highlighters sparingly; focus on key concepts rather than whole paragraphs.",
    "Listen to recorded lectures while doing chores or exercising.",
    "Draft a study schedule and stick to it as much as possible.",
    "Prioritize the most difficult or important topics first.",
    "Take a short walk during your breaks to clear your head.",
    "Use online resources and videos to supplement your learning.",
    "Don't be afraid to ask for help from teachers or tutors.",
    "Keep a 'distraction list' to write down unrelated thoughts and get back to studying.",
    "Use analogies to understand and remember complex ideas.",
    "Practice old exam papers to get a feel for the format and timing.",
    "Stay consistent with your study habits.",
    "Make sure your study desk is ergonomically comfortable.",
    "Limit caffeine intake; it can lead to crashes and anxiety.",
    "Understand the 'Big Picture' before diving into the details.",
    "Color-code your notes by topic or importance.",
    "Use the 2-minute rule: If a task takes less than 2 minutes, do it immediately.",
    "Find your most productive time of day and schedule your hardest work then.",
    "Keep your learning active: draw, speak, write, and do.",
    "Review the syllabus regularly to ensure you're on track.",
    "Try 'Dual Coding': Combine words and visuals to represent information.",
    "Use 'Interleaved Practice': Mix different types of problems or topics.",
    "Keep a growth mindset: View challenges as opportunities to learn.",
    "Avoid 'Pseudo-Studying': If you're not focused, take a real break.",
    "Use the 'Leitner System' for efficient flashcard review.",
    "Read out loud to engage more of your senses.",
    "Create your own practice questions as you study.",
    "Use 'Chunking': Group related information together to remember it more easily.",
    "Visualize what you're reading as if it were a movie in your head.",
    "Take advantage of 'dead time' like commuting or waiting in lines.",
    "Keep your goals visible near your study space.",
    "Reflect on what study methods work best for you and adapt.",
    "Focus on understanding the 'Why' behind facts.",
    "Use different colors of paper for different subjects.",
    "Try the '10-minute rule': Commit to 10 minutes, and often you'll keep going.",
    "Don't skip the 'easy' stuff; it's the foundation for the hard stuff.",
    "Keep a dictionary handy to look up unfamiliar words immediately.",
    "Use large whiteboards or windows to brainstorm and map out ideas.",
    "Practice deep breathing when you feel overwhelmed.",
    "Celebrate your progress, no matter how small.",
    "Keep a healthy balance between study and social life.",
    "Use apps to block distracting websites during study hours.",
    "Review the summary at the end of textbook chapters first.",
    "Make sure your study space has good lighting.",
    "Don't compare your progress to others; focus on your own journey.",
    "Stay curious and ask 'What if?'",
    "Use 'Spaced Repetition' software like Anki for long-term memorization.",
    "Keep a dedicated notebook for each subject.",
    "Remember that learning is a marathon, not a sprint."
];
