import { useState } from "react";
import { Button } from "@/components/ui/button";
import { FileDown, Loader2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { jsPDF } from "jspdf";
import type { Flashcard } from "@/lib/study-api";

interface ExportPdfButtonProps {
  flashcards: Flashcard[];
  title: string;
  variant?: "default" | "outline" | "secondary" | "ghost";
  size?: "default" | "sm" | "lg" | "icon";
}

export function ExportPdfButton({ 
  flashcards, 
  title, 
  variant = "outline",
  size = "sm" 
}: ExportPdfButtonProps) {
  const [isExporting, setIsExporting] = useState(false);
  const { toast } = useToast();

  const exportToPdf = async () => {
    if (flashcards.length === 0) {
      toast({
        title: "No flashcards to export",
        description: "Generate some flashcards first.",
        variant: "destructive",
      });
      return;
    }

    setIsExporting(true);

    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      const contentWidth = pageWidth - margin * 2;
      let yPosition = margin;

      // Title
      doc.setFontSize(20);
      doc.setFont("helvetica", "bold");
      doc.text(title || "Flashcards", pageWidth / 2, yPosition, { align: "center" });
      yPosition += 15;

      // Subtitle
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(128, 128, 128);
      doc.text(`${flashcards.length} cards • Generated by StudyAce`, pageWidth / 2, yPosition, { align: "center" });
      doc.setTextColor(0, 0, 0);
      yPosition += 15;

      // Flashcards
      flashcards.forEach((card, index) => {
        // Check if we need a new page
        if (yPosition > pageHeight - 60) {
          doc.addPage();
          yPosition = margin;
        }

        // Card number
        doc.setFontSize(10);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(100, 100, 100);
        doc.text(`Card ${index + 1}`, margin, yPosition);
        yPosition += 8;

        // Question
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(0, 0, 0);
        const questionLines = doc.splitTextToSize(`Q: ${card.question}`, contentWidth);
        doc.text(questionLines, margin, yPosition);
        yPosition += questionLines.length * 6 + 4;

        // Answer
        doc.setFontSize(11);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(60, 60, 60);
        const answerLines = doc.splitTextToSize(`A: ${card.answer}`, contentWidth);
        doc.text(answerLines, margin, yPosition);
        yPosition += answerLines.length * 5 + 4;

        // Hint (if exists)
        if (card.hint) {
          doc.setFontSize(10);
          doc.setFont("helvetica", "italic");
          doc.setTextColor(100, 100, 100);
          const hintLines = doc.splitTextToSize(`💡 Hint: ${card.hint}`, contentWidth);
          doc.text(hintLines, margin, yPosition);
          yPosition += hintLines.length * 5;
        }

        // Separator line
        yPosition += 5;
        doc.setDrawColor(220, 220, 220);
        doc.line(margin, yPosition, pageWidth - margin, yPosition);
        yPosition += 10;
      });

      // Footer on last page
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(
        `Generated on ${new Date().toLocaleDateString()} by StudyAce`,
        pageWidth / 2,
        pageHeight - 10,
        { align: "center" }
      );

      // Save
      const fileName = `${title || 'flashcards'}-${new Date().toISOString().split('T')[0]}.pdf`;
      doc.save(fileName);

      toast({
        title: "PDF exported",
        description: `Saved ${fileName}`,
      });
    } catch (error) {
      console.error('PDF export error:', error);
      toast({
        title: "Export failed",
        description: "There was an error creating the PDF.",
        variant: "destructive",
      });
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <Button 
      variant={variant} 
      size={size} 
      onClick={exportToPdf}
      disabled={isExporting || flashcards.length === 0}
    >
      {isExporting ? (
        <Loader2 className="h-4 w-4 animate-spin mr-2" />
      ) : (
        <FileDown className="h-4 w-4 mr-2" />
      )}
      Export PDF
    </Button>
  );
}
