// This file is automatically generated. Do not edit it directly.

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = new Proxy(
  {},
  {
    get() {
      throw new Error("Supabase has been removed: this project is running in pure Lovable/localStorage mode.");
    },
  }
);